AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: ./lambda
      Environment:
        Variables:
          S3_BUCKET_NAME: filestoring031
          DYNAMODB_TABLE_NAME: filemetadata
      Policies:
        - S3WritePolicy:
            BucketName: filestoring031
        - DynamoDBCrudPolicy:
            TableName: filemetadata
